# Generated by Django 5.1.1 on 2024-09-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('artwork_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_name', models.CharField(max_length=255)),
                ('episode_title', models.CharField(max_length=255)),
                ('transcript_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('podcast_name', 'episode_title')},
            },
        ),
    ]
