# Generated by Django 5.1.1 on 2024-09-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_transcriber_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='feed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
